name: Semantic Pull Request Check
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
